@authUid = dummy-firebase-uid-001

### Create a new Avatar
POST http://localhost:3000/api/avatars
Content-Type: application/json

{
  "authUid": "{{authUid}}",
  "name": "V",
  "theme": "dark"
}

### Fetch Avatar by UID
GET http://localhost:3000/api/avatars/{{authUid}}